// <auto-generated />
using System;
using Business.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Business.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20190819154727_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Business.Models.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .IsRequired();

                    b.Property<string>("IBAN")
                        .IsRequired();

                    b.Property<string>("RIB")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Business.Models.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CitiesID");

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal?>("Discount");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime?>("ExpiryDate");

                    b.Property<decimal?>("FromPrice");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Label");

                    b.Property<string>("LabelEn");

                    b.Property<bool>("PreOrder");

                    b.Property<Guid?>("ProductSmallImagesID");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("SuggestedCount");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<Guid>("UserID");

                    b.Property<string>("Value1");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
